<html lang="en">

<?php $this->render($this->components . "header.phtml"); ?>

<body>
<?php $this->render($this->components . "nav.phtml"); ?>
<section>
    <div class="container">
        <h1>1t.ie</h1>
        <form id="shorten_url_form">
            <label for="url">URL to shorten</label>
            <input type="text" name="url" id="url" placeholder="eg. https://google.com/">
            <button class="red inline fullwidth" type="submit" form="shorten_url_form">Shorten</button>
            <p class="error-warning"></p>
        </form>

        <div class="result">
            <h3>Here is your short link:</h3>
            <table>
                <tr>
                    <td id="shortened_link">Link</td>
                    <td class="copy">Copy to clipboard</td>
                </tr>
            </table>
        </div>
    </div>
</section>

<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="/src/js/scripts.js"></script>
</body>
</html>


