<footer class="footer">
    <h6 class="footer__title white uppercase">1t.ie</h6>
    <div class="content">
        <div class="divider"></div>

        <div class="row">
            <div class="col-4">
                <ul class="no-bullets">
                    <a href="/"><li class="footer__list-item">Home</li></a>
                    <a href="https://github.com/xy3/1t.ie#api"><li class="footer__list-item">API Docs</li></a>
                </ul>
            </div>
            <div class="col-4">
                <ul class="no-bullets">
                    <a href="/me"><li class="footer__list-item">Sign Up</li></a>
                    <a href="https://github.com/xy3/1t.ie"><li class="footer__list-item">GitHub Repo</li></a>
                </ul>
            </div>
            <div class="col-4">
                <ul class="no-bullets">
                    <a href="/contact"><li class="footer__list-item">Contact Us</li></a>
                    <a href="/me"><li class="footer__list-item">My Links</li></a>
                </ul>
            </div>
        </div>
    </div>
    <p class="subtitle">1t.ie &copy; <?php echo date("Y"); ?>.</p>
</footer>