<head>
    <meta charset="UTF-8">
    <meta http-equiv=“Pragma” content=”no-cache”>
    <meta http-equiv=“Expires” content=”-1″>
    <meta http-equiv=“CACHE-CONTROL” content=”NO-CACHE”>
    <title>1t.ie</title>
    <meta name="title" content="1t.ie">
    <meta property="og:title" content="1t.ie">
    <meta property="og:url" content="https://1t.ie/">
    <meta property="og:type" content="website">
<!--    <meta property="og:image" content="src/img/og_image.jpg">-->

<!--    <link href="https://fonts.googleapis.com/css2?family=Inconsolata:wght@400;700;900&display=swap" rel="stylesheet">-->
<!--    <link rel="stylesheet" href="src/css/style.css?v=2.95">-->
    <link rel="stylesheet" href="https://unpkg.com/cirrus-ui@0.5.5/dist/cirrus.min.css">
    <link rel="stylesheet" href="src/css/style.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:200,300,400,600,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <meta name="msapplication-TileColor" content="#ff2960">
    <meta name="theme-color" content="#000">
</head>
