<div id="header" class="header header-fill unselectable header-fixed no-transition header-dark header-animated">
        <div class="header-brand">
            <div class="nav-item">
                <a href="../../">
                    <h6 class="title">1t.ie</h6>
                </a>
            </div>
            <div class="nav-item nav-btn" id="header-btn">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div class="header-nav" id="header-menu">
            <div class="nav-left u-text-center">
                <div class="nav-item u-text-center">
                    <a href="https://github.com/xy3/1t.ie">
                    <span class="icon">
                    <i class="fab fa-wrapper fa-github"></i>
                    </span>
                    </a>
                </div>
            </div>
            <div class="nav-right u-text-center nav-menu">
                <div class="nav-item has-sub toggle-hover" id="dropdown">
                    <a class="nav-dropdown-link">Menu</a>
                    <ul class="dropdown-menu dropdown-animated" role="menu">
                        <li role="menu-item">
                            <a href="/">Homepage</a>
                        </li>
                        <li role="menu-item">
                            <a href="/me">My Account</a>
                        </li>
                        <li role="menu-item">
                            <a href="/contact">Contact</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>